"use client";

import { useEffect } from "react";
import { motion } from "framer-motion";
import Link from "next/link";
import { staggerContainer, bounceIn, slideUp } from "@/lib/animations";
import { useGameStore } from "@/stores/gameStore";

const bouncingEmojis = ["🎈", "🌟", "🎉", "📚", "🦄", "🌈", "🐾"];

const levels = [
  {
    id: "alphabet",
    href: "/games/alphabet",
    emoji: "🅰️",
    name: "Alphabet Island",
    x: "15%",
    y: "25%",
    color: "bg-grass",
    ring: "border-grass-light",
  },
  {
    id: "matching",
    href: "/games/matching",
    emoji: "🎯",
    name: "Match Woods",
    x: "calc(35% - 50px)",
    y: "75%",
    color: "bg-candy",
    ring: "border-candy-light",
  },
  {
    id: "spelling",
    href: "/games/spelling",
    emoji: "🐝",
    name: "Spelling Hive",
    x: "calc(70% - 110px)",
    y: "calc(60% - 40px)",
    color: "bg-sun-dark",
    ring: "border-sun",
  },
  {
    id: "numbers",
    href: "/games/numbers",
    emoji: "🔢",
    name: "Number Peak",
    x: "85%",
    y: "25%",
    color: "bg-sky",
    ring: "border-sky-light",
  },
  {
    id: "categories",
    href: "/games/categories",
    emoji: "🗺️",
    name: "Explorer Base",
    x: "75%",
    y: "calc(89% - 50px)",
    color: "bg-purple",
    ring: "border-purple-light",
  },
];

export default function HomePage() {
  const stars = useGameStore((s) => s.stars);
  const streakDays = useGameStore((s) => s.streakDays);
  const completedGames = useGameStore((s) => s.completedGames);
  const updateStreak = useGameStore((s) => s.updateStreak);

  useEffect(() => {
    updateStreak();
  }, [updateStreak]);

  return (
    <div className="max-w-5xl mx-auto px-4 py-8">
      {/* Header & Stats Section */}
      <div className="flex flex-col md:flex-row items-center justify-between gap-6 mb-8">
        <motion.div
          className="text-center md:text-left"
          variants={staggerContainer}
          initial="hidden"
          animate="visible"
        >
          <motion.h1 
            variants={bounceIn}
            className="font-display text-4xl sm:text-5xl font-extrabold text-night mb-2"
          >
            Welcome Explorer! 🚀
          </motion.h1>
          <motion.p
            variants={slideUp}
            className="font-hand text-xl sm:text-2xl text-night/70"
          >
            Choose your next learning adventure!
          </motion.p>
        </motion.div>

        {/* Stats */}
        <motion.div
          className="flex gap-4"
          variants={staggerContainer}
          initial="hidden"
          animate="visible"
        >
          <motion.div
            variants={bounceIn}
            className="flex flex-col items-center justify-center bg-white/80 backdrop-blur-sm border-2 border-sun p-3 rounded-2xl shadow-card min-w-[80px]"
          >
            <span className="text-3xl mb-1">⭐</span>
            <span className="font-display font-extrabold text-xl text-night">
              {stars}
            </span>
          </motion.div>
          <motion.div
            variants={bounceIn}
            className="flex flex-col items-center justify-center bg-white/80 backdrop-blur-sm border-2 border-candy p-3 rounded-2xl shadow-card min-w-[80px]"
          >
            <span className="text-3xl mb-1">🔥</span>
            <span className="font-display font-extrabold text-xl text-night">
              {streakDays}
            </span>
          </motion.div>
        </motion.div>
      </div>

      {/* World Map Container */}
      <motion.div
        initial={{ opacity: 0, y: 20, scale: 0.95 }}
        animate={{ opacity: 1, y: 0, scale: 1 }}
        transition={{ type: "spring", stiffness: 200, damping: 20 }}
        className="relative w-full aspect-square max-w-4xl mx-auto rounded-[40px] overflow-hidden border-8 border-white shadow-2xl bg-sky-light/20"
      >
        {/* Background Image generated by Nano Banana */}
        <div 
          className="absolute inset-0 bg-[url('/images/world-map.png')] bg-cover bg-center"
          aria-hidden="true"
        />

        {/* Shadow overlay to make levels pop slightly */}
        <div className="absolute inset-0 bg-night/5 pointer-events-none" />

        {/* Map Levels */}
        {levels.map((level, i) => {
          const isCompleted = completedGames.includes(level.href); // Simple mock check

          return (
            <motion.div
              key={level.id}
              initial={{ opacity: 0, scale: 0 }}
              animate={{ opacity: 1, scale: 1 }}
              transition={{ delay: 0.3 + i * 0.1, type: "spring" }}
              className="absolute"
              style={{ left: level.x, top: level.y, transform: "translate(-50%, -50%)" }}
            >
              <Link href={level.href} className="group relative flex flex-col items-center gap-2">
                {/* Level Title Bubble */}
                <motion.div 
                  initial={{ opacity: 0, y: 10 }}
                  whileInView={{ opacity: 1, y: 0 }}
                  className="absolute -top-12 bg-white/90 backdrop-blur-sm px-4 py-1.5 rounded-full shadow-card font-display font-bold text-night text-sm whitespace-nowrap opacity-0 group-hover:opacity-100 transition-opacity z-20 pointer-events-none"
                >
                  {level.name}
                  {/* Little bottom triangle pointer */}
                  <div className="absolute -bottom-2 left-1/2 -translate-x-1/2 border-solid border-t-white/90 border-t-8 border-x-transparent border-x-8 border-b-0" />
                </motion.div>

                {/* Level Button */}
                <motion.div
                  whileHover={{ scale: 1.15, rotate: [-5, 5, -5, 0] }}
                  whileTap={{ scale: 0.9 }}
                  className={`relative flex items-center justify-center w-16 h-16 sm:w-20 sm:h-20 rounded-full border-4 ${level.ring} ${level.color} shadow-btn cursor-pointer z-10`}
                >
                  {/* Pulsing ring behind uncompleted levels */}
                  {!isCompleted && (
                    <motion.div
                      animate={{ scale: [1, 1.4], opacity: [0.8, 0] }}
                      transition={{ duration: 1.5, repeat: Infinity }}
                      className={`absolute inset-0 rounded-full ${level.color} z-[-1] pointer-events-none`}
                    />
                  )}

                  <span className="text-3xl sm:text-4xl filter drop-shadow-md">{level.emoji}</span>
                  
                  {/* Completion checkmark (Mock) */}
                  {isCompleted && (
                    <div className="absolute -bottom-1 -right-1 bg-grass text-white text-xs w-6 h-6 flex items-center justify-center rounded-full border-2 border-white shadow-sm z-20">
                      ✓
                    </div>
                  )}
                </motion.div>
              </Link>
            </motion.div>
          );
        })}
      </motion.div>
    </div>
  );
}
